"""Suggerimento colore per la didascalia accanto all'illustrazione in apertura capitolo."""

from __future__ import annotations

COLOR_HINTS: dict[int, str] = {
    1: "il fango marrone argilloso che copre EleFranco dalla testa ai piedi",
    2: "gli occhialini rossi di Jack il Geco",
    3: "le banane gialle giganti appese all'albero",
    4: "la zanna di EleFranco lucente come l'oro",
    5: "la mantella patchwork di mille colori",
    6: "la luce verde e dorata delle lucciole nel cielo",
    7: "le ruote della bicicletta ben gonfie",
    8: "il fango marrone del maialino e l'acqua fresca della doccia",
    9: "i mille piedini colorati del bruco",
    10: "la ghianda marrone nel buco dell'albero",
    11: "il rosa delle guance di Mietta quando ride",
    12: "gli occhi di EleFranco che brillano di luce dorata",
    13: "il miele dorato appiccicoso e i biscotti sul ciuffo",
    14: "i papaveri rossi e le margherite bianche nei semi",
    15: "il latte di cocco bianco e i frutti di bosco nel gelato",
    16: "la pagina del fumetto piena di colori vivaci",
    17: "la segatura marrone sulla schiena di EleFranco",
    18: "l'arcobaleno magico sulla staccionata",
    19: "la lattuga verde croccante e lo spruzzo di fango sul ciuffo",
    20: "la limonata gialla fresca e profumata",
    21: "la scia di polline dorato lasciata dalle ali di Lalla",
    22: "le carote arancioni giganti nel campo e il fango marrone",
    23: "il miele dorato nel barattolo e il nastro giallo di Iris",
    24: "le mele rosse essiccate e la staffa di ferro lucente",
    25: "il riso bianco ammucchiato e la farina profumata del mulino",
    26: "la farina bianca sulla proboscide e i filoni dorati del forno",
    27: "le foglie verdi del platano e la mozzarella bianca lucente",
    28: "il palloncino rosso gonfio e il biglietto dorato della prima fila",
    29: "la polvere dorata delle falene e la costellazione luminosa del Cigno",
    30: "i bottoni a forma di stella dorati e il filo blu della mantella",
    31: "i limoni gialli caduti e il camaleonte verde brillante",
    32: "le ciabatte nuove blu e arancio e l'acqua azzurra della piscina",
    33: "i timbri colorati disposti a cuore e il francobollo dorato",
    34: "le foglie verdi che vibrano come arpa e le corde nuove della campanella",
    35: "le patate marroni grosse e la ruota del carretto nel fango",
    36: "le macchie arcobaleno luminose sul ciuffo e sulle scale bagnate",
    37: "il ghiaccio scolpito a forma di EleFranco e i cubetti nel secchio",
    38: "il basilico verde profumato e la terra marrone fertile",
    39: "i festoni colorati e la nebbiolina dolce del forno",
    40: "le uova chiare nel cesto e il calore dorato del tramonto",
    41: "il segnale rosso e il biglietto d'oro timbrato",
    42: "le alghe verdi sotto i tronchi e il cesto nuovo di salice",
    43: "le macchie di vernice rossa, gialla e blu sul selciato",
    44: "le bandierine colorate intorno al nido e la sabbia dorata disegnata",
    45: "le bolle di sapone iridescenti e la schiuma sul ciuffo",
    46: "il fieno dorato che cade sul campo e i semi nel sacchetto",
    47: "il nastro arcobaleno aggrovigliato e il fiocco gigante sulla bottega",
    48: "la farina bianca come neve e le ali blu elettriche della farfalla",
    49: "i coriandoli colorati e il nastro arancione di Franca",
    50: "i fuochi d'artificio dolci profumati e il festone centrale fiorito",
}

COLOR_HINT_PREFIX = (
    "Cerca questa immagine in fondo al libro per colorarla come preferisci. Ricorda: "
)
